/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModel.HoaDonDienNuoc;
import Services.IHoaDonDienNuocService;
import Services.Impl.HoaDonDienNuocViewModelServiceImpl;
import Utilities.XDate;
import ViewModel.HoaDonDienNuocViewModel;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Services.IHoaDonDienNuocViewModelService;
import Services.Impl.HoaDonDienNuocServiceImpl;
import ViewModel.PhongTroHDViewModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Bânbân
 */
public class QuanLyHoaDonDienNuoc extends javax.swing.JFrame {
    
    private DefaultTableModel dtm;
    private DefaultTableModel dtmP;
    private DefaultComboBoxModel dcbm;
    private List<HoaDonDienNuocViewModel> listHDVM;
    private List<HoaDonDienNuoc> listHD;
    private List<PhongTroHDViewModel> listPhong;
    private List<String> list;
    private IHoaDonDienNuocService iHoaDonDienNuocService;
    private IHoaDonDienNuocViewModelService iHoaDonDienNuocViewModelService;

    /**
     * Creates new form QuanLyHoaDonDienNuoc
     */
    public QuanLyHoaDonDienNuoc() {
        initComponents();
        dtm = new DefaultTableModel();
        dtmP = new DefaultTableModel();
        dcbm = new DefaultComboBoxModel();
        iHoaDonDienNuocService = new HoaDonDienNuocServiceImpl();
        iHoaDonDienNuocViewModelService = new HoaDonDienNuocViewModelServiceImpl();
        listHD = iHoaDonDienNuocService.getAll();
        list = iHoaDonDienNuocViewModelService.danhSachPhong();
        listHDVM = new ArrayList<>();
        listHDVM = iHoaDonDienNuocViewModelService.danhSach();
        listPhong = iHoaDonDienNuocViewModelService.danhSachHDPhong();
        dtm = (DefaultTableModel) this.tblHoaDonDienNuoc.getModel();
        dtmP = (DefaultTableModel) this.tblPhongTro.getModel();
        dcbm = (DefaultComboBoxModel) this.cboPhong.getModel();
        showDataTable(listHDVM);
        showDataTableP(listPhong);
        showComBoBox(list);
        txtMa.setEnabled(false);
        txtTongTien.setEnabled(false);
        txtGiaDien.setEnabled(false);
        txtGiaNuoc.setEnabled(false);
        
    }
    
    private void showDataTable(List<HoaDonDienNuocViewModel> list) {
        dtm.setRowCount(0);
        for (HoaDonDienNuocViewModel hddnvm : list) {
            dtm.addRow(hddnvm.toDataRow());
        }
    }
    
    private void showDataTableP(List<PhongTroHDViewModel> list) {
        dtmP.setRowCount(0);
        for (PhongTroHDViewModel pthdvm : list) {
            dtmP.addRow(pthdvm.toDataRow());
        }
    }
    
    private void showComBoBox(List<String> list) {
        dcbm.removeAllElements();
        for (String s : list) {
            dcbm.addElement(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTT = new javax.swing.ButtonGroup();
        btnSoSanhTT = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDien = new javax.swing.JTextField();
        txtGiaDien = new javax.swing.JTextField();
        txtNuoc = new javax.swing.JTextField();
        txtGiaNuoc = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtKhachDua = new javax.swing.JTextField();
        txtThieu = new javax.swing.JTextField();
        rdoChuaTT = new javax.swing.JRadioButton();
        rdoDaTT = new javax.swing.JRadioButton();
        btnTaoHD = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        dchNgayTao = new com.toedter.calendar.JDateChooser();
        cboPhong = new javax.swing.JComboBox<>();
        btnXuatPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonDienNuoc = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPhongTro = new javax.swing.JTable();
        rdoTatCa = new javax.swing.JRadioButton();
        rdoDaTra = new javax.swing.JRadioButton();
        rdoChuaTra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý hóa đơn điện nước");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HÓA ĐƠN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel2.setText("Mã HĐ");

        jLabel4.setText("Phòng");

        jLabel5.setText("Ngày đóng");

        jLabel6.setText("Tên khách hàng");

        jLabel7.setText("Điện");

        jLabel8.setText("Nước");

        jLabel9.setText("Giá");

        jLabel10.setText("Giá");

        jLabel11.setText("Trạng thái");

        jLabel12.setText("Tổng tiền");

        jLabel13.setText("Khách đưa");

        jLabel14.setText("Thiếu");

        txtTongTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTongTienMouseClicked(evt);
            }
        });

        txtKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhachDuaKeyReleased(evt);
            }
        });

        btnTT.add(rdoChuaTT);
        rdoChuaTT.setSelected(true);
        rdoChuaTT.setText("Chưa thanh toán");

        btnTT.add(rdoDaTT);
        rdoDaTT.setText("Đã thanh toán");

        btnTaoHD.setText("Tạo hóa đơn");
        btnTaoHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoHDMouseClicked(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseClicked(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoiMouseClicked(evt);
            }
        });

        cboPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhongMouseClicked(evt);
            }
        });

        btnXuatPDF.setText("Xuất hóa đơn");
        btnXuatPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatPDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenKH)
                            .addComponent(dchNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoChuaTT)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDaTT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTaoHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXuatPDF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaDien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKhachDua))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(29, 29, 29)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dchNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rdoChuaTT)
                    .addComponent(rdoDaTT))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTaoHD)
                    .addComponent(btnXuatPDF))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tblHoaDonDienNuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Phòng", "Tên khách hàng", "Ngày tạo", "Tổng tiền", "Tiền thiếu/Đủ", "Trạng thái"
            }
        ));
        tblHoaDonDienNuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonDienNuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonDienNuoc);

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        tblPhongTro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên phòng", "Tên khách thuê", "Số tầng", "Trạng thái"
            }
        ));
        tblPhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongTroMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPhongTro);

        btnSoSanhTT.add(rdoTatCa);
        rdoTatCa.setSelected(true);
        rdoTatCa.setText("Tất cả");
        rdoTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoTatCaMouseClicked(evt);
            }
        });

        btnSoSanhTT.add(rdoDaTra);
        rdoDaTra.setText("Đã thanh toán");
        rdoDaTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoDaTraMouseClicked(evt);
            }
        });

        btnSoSanhTT.add(rdoChuaTra);
        rdoChuaTra.setText("Chưa thanh toán");
        rdoChuaTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoChuaTraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoTatCa)
                                .addGap(27, 27, 27)
                                .addComponent(rdoDaTra)
                                .addGap(33, 33, 33)
                                .addComponent(rdoChuaTra))
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTatCa)
                    .addComponent(rdoDaTra)
                    .addComponent(rdoChuaTra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonDienNuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonDienNuocMouseClicked
        // TODO add your handling code here:

        int rowIndex = tblHoaDonDienNuoc.getSelectedRow();
        if (rowIndex >= 0 && rowIndex <= listHD.size()) {
            detailHoaDonDienNuoc(rowIndex);
        }
        tblPhongTro.setEnabled(false);
        btnCapNhat.setEnabled(true);
    }//GEN-LAST:event_tblHoaDonDienNuocMouseClicked

    private void btnTaoHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoHDMouseClicked
        // TODO add your handling code here:
        if (checkValidate() && checkMa()) {
            HoaDonDienNuoc hddn = getDataFormView();
            txtTongTien.setText(getTongTien() + "");
            iHoaDonDienNuocService.them(hddn);
            listHDVM = iHoaDonDienNuocViewModelService.danhSach();
            showDataTable(listHDVM);
            JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công!");
            btnCapNhat.setEnabled(true);
        }
    }//GEN-LAST:event_btnTaoHDMouseClicked

    private void btnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseClicked
        // TODO add your handling code here:
        String ma = txtMa.getText();
        int rowIndex = tblHoaDonDienNuoc.getSelectedRow();
        if (rowIndex >= 0) {
            HoaDonDienNuoc hddn = getDataFormView();
//            txtTongTien.setText(getTongTien() + "");
            iHoaDonDienNuocService.sua(ma, hddn);
            listHDVM = iHoaDonDienNuocViewModelService.danhSach();
            showDataTable(listHDVM);
            JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần sửa");
        }
    }//GEN-LAST:event_btnCapNhatMouseClicked

    private void btnMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoiMouseClicked
        // TODO add your handling code here:
        txtMa.setText("");
        cboPhong.setSelectedItem(null);
        dchNgayTao.setDate(null);
        txtDien.setText("");
        txtNuoc.setText("");
        txtTongTien.setText("");
        txtKhachDua.setText("");
        txtTenKH.setText("");
        txtGiaDien.setText("");
        txtGiaNuoc.setText("");
        txtThieu.setText("");
        btnTT.clearSelection();
        showDataTable(listHDVM);
        showDataTableP(listPhong);
        tblPhongTro.setEnabled(true);
        btnSoSanhTT.clearSelection();

    }//GEN-LAST:event_btnMoiMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        String ten = txtTimKiem.getText().trim();
        listHDVM = iHoaDonDienNuocViewModelService.timtheoten(ten);
        showDataTable(listHDVM);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhachDuaKeyReleased
        // TODO add your handling code here:
        double tienKhachDua = Double.parseDouble(txtKhachDua.getText());
        double thieu = 0;
        thieu = tienKhachDua - getTongTien();
        txtThieu.setText(String.valueOf(thieu));
    }//GEN-LAST:event_txtKhachDuaKeyReleased

    private void tblPhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongTroMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblPhongTro.getSelectedRow();
        if (rowIndex >= 0 && rowIndex <= listPhong.size()) {
            detailPhong(rowIndex);
        }
    }//GEN-LAST:event_tblPhongTroMouseClicked

    private void txtTongTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTongTienMouseClicked
        // TODO add your handling code here:
        txtTongTien.setText(String.valueOf(getTongTien()));
    }//GEN-LAST:event_txtTongTienMouseClicked

    private void cboPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhongMouseClicked
        // TODO add your handling code here:
        int index = cboPhong.getSelectedIndex();
        if (index == -1) {
            return;
        }
        String giaDien = iHoaDonDienNuocViewModelService.getGiaDien(cboPhong.getItemAt(index));
        txtGiaDien.setText(giaDien);
        String giaNuoc = iHoaDonDienNuocViewModelService.getGiaNuoc(cboPhong.getItemAt(index));
        txtGiaNuoc.setText(giaNuoc);
    }//GEN-LAST:event_cboPhongMouseClicked

    private void rdoTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoTatCaMouseClicked
        // TODO add your handling code here:
        listHDVM = iHoaDonDienNuocViewModelService.danhSach();
        showDataTable(listHDVM);
    }//GEN-LAST:event_rdoTatCaMouseClicked

    private void rdoDaTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoDaTraMouseClicked
        // TODO add your handling code here:
        listHDVM = iHoaDonDienNuocViewModelService.listHoaDonDienNuocTT(1);
        showDataTable(listHDVM);
    }//GEN-LAST:event_rdoDaTraMouseClicked

    private void rdoChuaTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoChuaTraMouseClicked
        // TODO add your handling code here:
        listHDVM = iHoaDonDienNuocViewModelService.listHoaDonDienNuocTT(0);
        showDataTable(listHDVM);
    }//GEN-LAST:event_rdoChuaTraMouseClicked

    private void btnXuatPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatPDFMouseClicked
        // TODO add your handling code here:
        String path = "";
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = jFileChooser.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            jFileChooser.getSelectedFile().getPath();
        }
        
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "hoadondiennuoc.pdf"));
            
            doc.open();
            
            PdfPTable tbl = new PdfPTable(8);
            tbl.addCell("STT");
            tbl.addCell("Mã hóa đơn");
            tbl.addCell("Phòng");
            tbl.addCell("Tên khách hàng");
            tbl.addCell("Ngày tạo");
            tbl.addCell("Tổng tiền");
            tbl.addCell("Tiền thiếu");
            tbl.addCell("Trạng thái");
            
            for (int i = 0; i < tblHoaDonDienNuoc.getRowCount(); i++) {
                int stt = (int) tblHoaDonDienNuoc.getValueAt(i, 0);
                String ma = tblHoaDonDienNuoc.getValueAt(i, 1).toString();
                String phong = tblHoaDonDienNuoc.getValueAt(i, 2).toString();
                String tenKH = tblHoaDonDienNuoc.getValueAt(i, 3).toString();
                Date ngayTao = (Date) tblHoaDonDienNuoc.getValueAt(i, 4);
                double tongTien = (double) tblHoaDonDienNuoc.getValueAt(i, 5);
                double tienThua = (double) tblHoaDonDienNuoc.getValueAt(i, 6);
                String trangThai = tblHoaDonDienNuoc.getValueAt(i, 7).toString();
                tbl.addCell(stt + "");
                tbl.addCell(ma);
                tbl.addCell(phong);
                tbl.addCell(tenKH);
                tbl.addCell(ngayTao + "");
                tbl.addCell(tongTien + "");
                tbl.addCell(tienThua + "");
                tbl.addCell(trangThai + "");
            }
            doc.add(tbl);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }//GEN-LAST:event_btnXuatPDFMouseClicked
    private void detailHoaDonDienNuoc(int index) {
        HoaDonDienNuocViewModel hddnvm = listHDVM.get(index);
        txtMa.setText(hddnvm.getMaHD());
        cboPhong.setSelectedItem((hddnvm.getTenPhong()));
        dchNgayTao.setDate(hddnvm.getNgayDong());
        txtTenKH.setText(hddnvm.getTenKH());
        txtDien.setText(hddnvm.getSoDien() + "");
        txtGiaDien.setText(hddnvm.getGiaDien() + "");
        txtNuoc.setText(hddnvm.getSoNuoc() + "");
        txtGiaNuoc.setText(hddnvm.getGiaNuoc() + "");
        txtTongTien.setText(getTongTien() + "");
        txtThieu.setText(hddnvm.getTienThieu() + "");
        if (hddnvm.isTrangThai()) {
            rdoDaTT.setSelected(true);
        } else {
            rdoChuaTT.setSelected(true);
        }
        
    }
    
    private void detailPhong(int index) {
        PhongTroHDViewModel pthdvm = listPhong.get(index);
        cboPhong.setSelectedItem(pthdvm.getTenPhong());
        txtTenKH.setText(pthdvm.getTenKH());
    }
    
    private HoaDonDienNuoc getDataFormView() {
        String maHD = "HĐ00";
        int stt = 1;
        listHD = iHoaDonDienNuocService.getAll();
        for (HoaDonDienNuoc hddn : listHD) {
            stt++;
        }
        HoaDonDienNuoc hddn = new HoaDonDienNuoc();
        UUID id = UUID.randomUUID();
        hddn.setId(String.valueOf(id));
        String ma = maHD + String.valueOf(stt);
        hddn.setMa(ma);
        Date ngayDong = dchNgayTao.getDate();
        hddn.setNgayTao(ngayDong);
        String idPhong = iHoaDonDienNuocViewModelService.getIDByPhong(cboPhong.getSelectedItem().toString());
        hddn.setIdPhongTro(idPhong);
        String tenKH = iHoaDonDienNuocViewModelService.getIDByKH(txtTenKH.getText());
        hddn.setIdKH(tenKH);
        String hopDong = iHoaDonDienNuocViewModelService.getIDByHD(cboPhong.getSelectedItem().toString());
        hddn.setIdHopDong(hopDong);
        double tongTien = Double.parseDouble(txtTongTien.getText());
        hddn.setTongTien(tongTien);
        double tienThieu = Double.parseDouble(txtThieu.getText());
        hddn.setTienThieu(tienThieu);
        int soDien = Integer.parseInt(txtDien.getText());
        hddn.setSoDien(soDien);
        int soNuoc = Integer.parseInt(txtNuoc.getText());
        hddn.setSoNuoc(soNuoc);
        boolean trangThai = false;
        if (rdoDaTT.isSelected()) {
            trangThai = true;
        }
        hddn.setTrangThai(trangThai);
        return hddn;
    }
    
    private boolean checkValidate() {
        if (txtDien.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện không được bỏ trống!");
            return false;
        } else if (!txtDien.getText().trim().replace(".", "").matches("\\d+") || Integer.parseInt(txtDien.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Số điện phải lớn hơn 0!");
            return false;
        } else if (txtNuoc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số nước không được bỏ trống!");
            return false;
        } else if (!txtNuoc.getText().trim().replace(".", "").matches("\\d+") || Integer.parseInt(txtNuoc.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Số nước phải lớn hơn 0!");
            return false;
        }
        return true;
    }
    
    public double getTongTien() {
        double tongTien = 0;
        double tienDien = Integer.parseInt(txtDien.getText()) * Double.parseDouble(txtGiaDien.getText());
        double tienNuoc = Integer.parseInt(txtNuoc.getText()) * Double.parseDouble(txtGiaNuoc.getText());
        tongTien = tienDien + tienNuoc;
        return tongTien;
    }
    
    public boolean checkMa() {
        String ma = txtMa.getText().trim();
        for (HoaDonDienNuocViewModel hddnvm : listHDVM) {
            if (hddnvm.getMaHD().equalsIgnoreCase(ma)) {
                JOptionPane.showMessageDialog(this, "Mã Hóa Đơn đã tồn tại!");
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonDienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDonDienNuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnMoi;
    private javax.swing.ButtonGroup btnSoSanhTT;
    private javax.swing.ButtonGroup btnTT;
    private javax.swing.JButton btnTaoHD;
    private javax.swing.JButton btnXuatPDF;
    private javax.swing.JComboBox<String> cboPhong;
    private com.toedter.calendar.JDateChooser dchNgayTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoChuaTT;
    private javax.swing.JRadioButton rdoChuaTra;
    private javax.swing.JRadioButton rdoDaTT;
    private javax.swing.JRadioButton rdoDaTra;
    private javax.swing.JRadioButton rdoTatCa;
    private javax.swing.JTable tblHoaDonDienNuoc;
    private javax.swing.JTable tblPhongTro;
    private javax.swing.JTextField txtDien;
    private javax.swing.JTextField txtGiaDien;
    private javax.swing.JTextField txtGiaNuoc;
    private javax.swing.JTextField txtKhachDua;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNuoc;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtThieu;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
